M48
; DRILL file {KiCad 6.0.0-d3dd2cf0fa~116~ubuntu20.04.1} date Sun 09 Jan 2022 06:21:25 PM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-09T18:21:25+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0-d3dd2cf0fa~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.986
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.988
%
G90
G05
T1
X105.555Y-97.11
X105.555Y-102.89
T2
X123.64Y-93.134
X123.64Y-95.166
T3
X118.56Y-94.15
T0
M30
